
(define-foreign-type sfShape "sfShape" '())

#|
sf-shape-create
sf-shape-create-line
sf-shape-create-rectangle
sf-shape-create-circle
sf-shape-copy
sf-shape-destroy
sf-shape-set-x
sf-shape-set-y
sf-shape-set-position
sf-shape-set-scale-x
sf-shape-set-scale-y
sf-shape-set-scale
sf-shape-set-rotation
sf-shape-set-origin
sf-shape-set-color
;sf-shape-set-blend-mode
sf-shape-get-x
sf-shape-get-y
sf-shape-get-scale-x
sf-shape-get-scale-y
sf-shape-get-rotation
sf-shape-get-origin-x
sf-shape-get-origin-y
;sf-shape-get-color
;sf-shape-get-blend-mode
sf-shape-move
sf-shape-scale
sf-shape-rotate
sf-shape-transform-to-local
sf-shape-transform-to-global
sf-shape-add-point
sf-shape-enable-fill
sf-shape-enable-outline
sf-shape-set-outline-thickness
sf-shape-get-outline-thickness
sf-shape-get-points-count
sf-shape-get-point-position
sf-shape-get-point-outline-color
sf-shape-set-point-position
sf-shape-set-point-color
sf-shape-set-point-outline-color
|#
