;;;; sfml.import.scm - GENERATED BY CHICKEN 4.7.0 -*- Scheme -*-

(eval '(import scheme chicken foreign))
(##sys#register-compiled-module
  'sfml
  (list)
  '((sf-default-style . sfml#sf-default-style)
    (sf-render-window-create . sfml#sf-render-window-create)
    (sf-render-window-destroy . sfml#sf-render-window-destroy)
    (sf-texture-create-from-file . sfml#sf-texture-create-from-file)
    (sf-texture-destroy . sfml#sf-texture-destroy)
    (sf-sprite-create . sfml#sf-sprite-create)
    (sf-sprite-set-texture . sfml#sf-sprite-set-texture)
    (sf-sprite-destroy . sfml#sf-sprite-destroy)
    (sf-render-window-clear . sfml#sf-render-window-clear)
    (sf-render-window-draw-sprite . sfml#sf-render-window-draw-sprite)
    (sf-render-window-display . sfml#sf-render-window-display)
    (sf-render-window-poll-event . sfml#sf-render-window-poll-event)
    (sf-render-window-is-opened . sfml#sf-render-window-is-opened)
    (sf-render-window-close . sfml#sf-render-window-close)
    (sf-event-create . sfml#sf-event-create)
    (sf-event-closed? . sfml#sf-event-closed?)
    (sf-event-key-pressed? . sfml#sf-event-key-pressed?))
  (list)
  (list))

;; END OF FILE
